### PR TITLE
fix: wrong context.commits when have multiple releases commit

### PR DESCRIPTION
**Pull request by iporsut**
Fix bug: https://github.com/qiwi/multi-semantic-release/issues/40

### CODE REVIEW

**Comment by antongolub** [comment]
Hey, @iporsut,

Looks reasonable. Could you provide a test for this fix? If not, it's ok, we can always add it later.

**Comment by iporsut** [comment]
@antongolub Yes, I will add a test case before merge it.

**Comment by iporsut** [comment]
@antongolub I added a test case.

**Review by antongolub — APPROVED** [review]
@iporsut, thanks a lot!

LGTM

**Pull request merged**
